### PR TITLE
feat: README for the repository itself

### PR DESCRIPTION
**Pull request by castelao**
Minimal information and pointing to OceanGlidersCommunity repository for the general resources.

### CODE REVIEW

**Review by soerenthomsen — APPROVED** [review]

**Review by soerenthomsen — CHANGES_REQUESTED** [review]
Now I am confused. I first thought we plan to remove the [OceanGliders](https://github.com/OceanGlidersCommunity/OceanGliders) repo including the readme there and just keep the .github/profile/Readme up to date? Which is fine for me.

For sure we should not have two "main readme" files. There is nothing else in the OceanGliders repo beside the readme at the moment.

**Comment by castelao** [comment]
Yeah, I don't have a clear opinion about this yet. I think it is important to have a central place for general OceanGliders Community discussions. For instance, the code of conduct should move to there. At this moment I'm seeing the .github repo as an organization configuration and I guess that they will bring more resources to here.

What about using .github to setup GitHub and the OceanGlidersCommunity for our community stuff? If we do like that, the .github job would be to provide the short intro on the first page, while the readme of the OceanGlidersCommunity would provide a longer and more detailed readme, plus ...

**Comment by soerenthomsen** [comment]
> What about using .github to setup GitHub and the OceanGlidersCommunity for our community stuff? If we do like that, the .github job would be to provide the short intro on the first page, while the readme of the OceanGlidersCommunity would provide a longer and more detailed readme, plus ...

Yes let's do it like this!

**Review by soerenthomsen — APPROVED** [review]

**Review by ptestor — CHANGES_REQUESTED** [review]
insert OceanGliders URL somewhere?

**Review by soerenthomsen — APPROVED** [review]

**Pull request merged**
